[package]
name = "wled_backup"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
mdns-sd = "0.13.9"
reqwest = { version = "0.12.20", features = ["blocking"] }
tokio = "1.45.1"
