# https://docs.docker.com/go/compose-spec-reference/

services:
  wled_backup:
    build:
      context: .
      target: final
    restart: unless-stopped
    ports:
      - 5800:5800
    volumes:
      - ./wled_backup:/backup
